sudo: false
language: node_js

cache:
  directories:
    - node_modules

branches:
  only:
    - master

notifications:
  email:
    on_failure: change

node_js:
  - stable

addons:
  chrome: stable
  code_climate:
    repo_token:  $CC_TEST

before_script:
  - npm install codeclimate-test-reporter istanbul karma-cli -g
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run test
  - npm run build.prod
  - istanbul cover ./node_modules/karma/bin/karma start karma.config.js

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
